name: Test Project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test ${{ matrix.lang }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lang: [rust, zig]
        year: [2023]  # Add years as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ${{ matrix.lang }}
        if: matrix.lang == 'rust'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Zig
        if: matrix.lang == 'zig'
        run: sudo apt-get install -y zig

      - name: Build and test Rust
        if: matrix.lang == 'rust'
        run: |
          for dir in src/${{ matrix.year }}/day-*/rust/*; do
            cd "$dir" && cargo test --all || exit 1
          done

      - name: Build and test Zig
        if: matrix.lang == 'zig'
        run: |
          for dir in src/${{ matrix.year }}/day-*/zig/*; do
            cd "$dir" && zig test *.zig || exit 1
          done
